name: Build and release binaries for PIE

on:
  push:
    tags:
      - '*'

permissions:
  contents: read

jobs:
  create-draft-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-tags: 'true'
          ref: ${{ github.ref }}
          submodules: recursive
      - name: Create source archive with submodules
        run: |
          ARCHIVE_NAME="${{ github.event.repository.name }}-${{ github.ref_name }}"
          git archive --format=tar --prefix="${ARCHIVE_NAME}/" HEAD > "${ARCHIVE_NAME}.tar"
          git submodule foreach --recursive \
            'git archive --format=tar --prefix="'"${ARCHIVE_NAME}"'/${sm_path}/" HEAD | tar --concatenate --file="${GITHUB_WORKSPACE}/${ARCHIVE_NAME}.tar"'
          gzip "${ARCHIVE_NAME}.tar"
      - name: Create draft release from tag
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          ARCHIVE_NAME="${{ github.event.repository.name }}-${{ github.ref_name }}"
          gh release create "${{ github.ref_name }}" --title "${{ github.ref_name }}" --draft --notes-from-tag \
            "${ARCHIVE_NAME}.tar.gz#Source with submodules"

  add-pie-binaries:
    needs: [ create-draft-release ]
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system:
          - ubuntu-latest
          - macos-latest
        php-versions:
          - '8.1'
          - '8.2'
          - '8.3'
          - '8.4'
          - '8.5'
        zts-mode:
          - ts
          - nts
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          submodules: recursive
      - name: Setup PHP
        uses: shivammathur/setup-php@accd6127cb78bee3e8082180cb391013d204ef9f # v2.37.0
        with:
          php-version: ${{ matrix.php-versions }}
        env:
          phpts: ${{ matrix.zts-mode }}
      - name: Build and release
        uses: php/pie-ext-binary-builder@5298761950f63c7e9565ed7004e922b346e4386c # 0.0.3
        with:
          release-tag: ${{ github.ref_name }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          configure-flags: '--enable-colopl_timeshifter'
          build-path: 'ext'
